ShibaStoreProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShibaStoreProject.Controllers
{
    public class HomeController : Controller
    {

        StoreDBEntities db = new StoreDBEntities();

        public ActionResult Index()
        {
            
            return View(db.Dogs.ToList());
        }
    }
}

ShibaStoreProject/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShibaStoreProject.Controllers
{
    public class LoginController : Controller
    {
        StoreDBEntities db = new StoreDBEntities();

        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [HttpPost]
        public ActionResult Index(string username, string password)
        {

            
            if (db.Users.Any(o => o.Username == username && o.Password == password))
            {

                User user = db.Users.First(i => i.Username == username && i.Password == password);
                
                System.Web.HttpContext.Current.Session.Add("sessionID", user.UserID.ToString());

                System.Web.Security.FormsAuthentication.RedirectFromLoginPage(username, false);
                return RedirectToAction("SuccessfulLogin");
            }
            ViewBag.Error = "You have entered incorrect information. :(";
            return View();
        }

        public ActionResult SuccessfulLogin()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        public ActionResult Logout()
        {
            System.Web.Security.FormsAuthentication.SignOut();
            Session.Clear();
            return RedirectToAction("Index", "Home");

        }
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register(string username, string password, string passwordRepeat)
        {
            if (db.Users.Any(o => o.Username == username)){
                ViewBag.Error = "Username already exists. :(";
                return View();
            }else if(password != passwordRepeat)
            {
                ViewBag.Error = "Password does not match. :(";
                return View();
            }
            else
            {
                User newUser = new User();
                newUser.Username = username;
                newUser.Password = password;
                db.Users.Add(newUser);
                db.SaveChanges();
                System.Web.HttpContext.Current.Session.Add("registerVar", "registered");
                return RedirectToAction("SuccessfulRegister");

            }
        }

        public ActionResult SuccessfulRegister()
        {
            if(System.Web.HttpContext.Current.Session["registerVar"] != null)
            {
                return View();

            }
            return RedirectToAction("Index", "Home");
        }
    }
    
}

ShibaStoreProject/Controllers/MyPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShibaStoreProject.Controllers
{
    public class MyPageController : Controller
    {

        StoreDBEntities db = new StoreDBEntities();

        // GET: MyPage

        [Authorize]
        public ActionResult Index()
        {

            List<Dog> doglist = new List<Dog>();
            foreach (var dogs in db.Dogs)
            {
                var uID = Convert.ToInt32(System.Web.HttpContext.Current.Session["sessionID"]);
                User users = db.Users.First(i => i.UserID == uID);

                if (db.Dogs.FirstOrDefault(i => i.DogID == dogs.DogID && i.Users.Any(t => t.UserID == uID)) != null)
                {
                    doglist.Add(dogs);
                }
            }
            return View(doglist);
        }
       [HttpPost]
       public ActionResult Index(int dogID)
        {
            var uID = Convert.ToInt32(System.Web.HttpContext.Current.Session["sessionID"]);
            User users = db.Users.First(i => i.UserID == uID);
            Dog dog = db.Dogs.First(i => i.DogID == dogID);
            dog.Users.Remove(users);
            db.SaveChanges();

            List<Dog> doglist = new List<Dog>();
            foreach (var dogs in db.Dogs)
            {
                

                if (db.Dogs.FirstOrDefault(i => i.DogID == dogs.DogID && i.Users.Any(t => t.UserID == uID)) != null)
                {
                    doglist.Add(dogs);
                }
            }
            return View(doglist);
        }
    }
}

ShibaStoreProject/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShibaStoreProject.Controllers
{
    public class StoreController : Controller
    {

        StoreDBEntities db = new StoreDBEntities();

        public ActionResult Index()
        {

    
            return View(db.Dogs.ToList());
        }
        
        [HttpPost]
        public ActionResult Index(int dogID)
        {

            Dog dog = db.Dogs.First(i => i.DogID == dogID);
            int uID = Convert.ToInt32(System.Web.HttpContext.Current.Session["sessionID"]);
            User user = db.Users.First(i => i.UserID == uID);
            dog.Users.Add(user);
            db.SaveChanges();
            return View(db.Dogs.ToList());
        }
    }
}

ShibaStoreProject/Views/Home/Index.cshtml
@model List<ShibaStoreProject.Dog>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Fredoka+One|Open+Sans:700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">


</head>
<body>

    <div id="mainpage">
        <div class="shibaheader">
            <div class="headertext">
                <a class="textlefttitle" style="border-right: solid 2px white; padding-right: 1.5%;" onclick="location.href='@Url.Action("Index", "Home")'">Shiba Central</a>
                <a class="textleft" style="margin-left:1.3%;" onclick="location.href='@Url.Action("Index", "Store")'">Store</a>
                <a class="textleft" href="https://www.w3schools.com">Community</a>
                @if (User.Identity.IsAuthenticated)
                {
                    <a class="textright" onclick="location.href='@Url.Action("Index", "MyPage")'">My Page</a>

                    <a class="textright" onclick="location.href='@Url.Action("Logout", "Login")'">Logout</a>
                }
                else
                {
                    <a class="textright" onclick="location.href='@Url.Action("Register", "Login")'">Register</a>

                    <a class="textright" onclick="location.href='@Url.Action("Index", "Login")'">Login</a>
                }


            </div>
        </div>

        <div style="margin-bottom: 0%; height:auto; ">

            <img class="shibaimgmain" src="~/Resources/Images/mainshiba.png" />
            <div class="text-block">
                <h1 style="margin-bottom: 0;">"Woof woof"</h1>
                <p style="margin-bottom: 0; margin-top: 0;">- This dog, probably</p>
            </div>
        </div>

    </div>
    <div id="featureddogs">

        <h1 class="featureddogstitle">FEATURED DOGS</h1>
        <div class="doglist">
            <ul class="doglistul" style="list-style:none; padding-left: 0; ">
                @for (int i = 0; i < Model.Count(); i++)
                {
                    <li>
                        <div class="dogcontainer">

                            <a onclick="location.href='@Url.Action("Index", "Store")'"><img src="@("/Resources/Images/" + Model[i].ImageName)" class="containerimage" /></a>
                            <div class="containertextbox">
                                <p class="containertext">@Model[i].DogName</p>
                            </div>
                        </div>
                    </li>
                    
                }


            </ul>

        </div>
        <a onclick="location.href='@Url.Action("Index", "Store")'" class="viewdogbutton"><p class="viewdogbuttontext">View all dogs</p></a>
    </div>
    <div id="pagemiddle">
        <h1 class="middletexttitle">
            Welcome to Shiba Central
        </h1>
        <p class="middletextbody">
            The Shiba Inu (柴犬, Japanese: [ɕiba̠ inɯ̟ᵝ]) is the smallest of the six original and distinct spitz breeds of dog native to Japan.[1]

            A small, agile dog that copes very well with mountainous terrain, the Shiba Inu was originally bred for hunting.[1][2] It looks similar to and is often mistaken for other Japanese dog breeds like the Akita Inu or Hokkaido, but the Shiba Inu is a different breed with a distinct blood line, temperament and smaller size than other Japanese dog breeds.[3][4][5]
        </p>
        <p class="socialmediatext">Follow us on social media</p>

        <div class="socialmedialist">
            <ul style="list-style:none; padding-left: 0;">
                <li><a href="http://www.youareanidiot.org/"><img src="~/Resources/Images/facebookicon.png" class="socialmediaitem" /></a></li>
                <li><a href="http://www.youareanidiot.org/"><img src="~/Resources/Images/instagramicon.png" class="socialmediaitem" /></a></li>
                <li><a href="http://www.youareanidiot.org/"><img src="~/Resources/Images/youtubeicon.png" class="socialmediaitem" /></a></li>
                <li><a href="http://www.youareanidiot.org/"><img src="~/Resources/Images/twittericon.png" class="socialmediaitem" /></a></li>


            </ul>
        </div>
    </div>


    <div id="pagefooter">
        <img class="shibahead" src="~/Resources/Images/shibahead.png" />
        <h1 class="footertitle">SHIBA CENTRAL™</h1>
        <ul class="footerlist">
            <li style="border:none;"><a href="http://www.youareanidiot.org/"><p>CAREERS</p></a></li>
            <li><a href="http://www.youareanidiot.org/"><p>ABOUT</p></a></li>
            <li><a href="http://www.youareanidiot.org/"><p>SUPPORT</p></a></li>
            <li><a href="http://www.youareanidiot.org/"><p>CONTACT US</p></a></li>
            <li><a href="http://www.youareanidiot.org/"><p>PRESS</p></a></li>

        </ul>

        <p class="legaltext" style="font-size: 15px; margin-top: 1.7%; margin-bottom: 2%;">
            ©2018 SHIBA CENTRAL, INC. ALL RIGHTS RESERVED.
            <br />
            All trademarks referenced herein are the properties of their respective owners.
        </p>
    </div>
</body>
</html>

ShibaStoreProject/Views/Login/SuccessfulLogin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Fredoka+One|Open+Sans:700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
</head>
<body>
    <div class="backgroundimage">
        <div class="shibastoretop">
            <div id="mainpage">
                <div class="shibaheaderstore">
                    <div class="headertext">
                        <a class="textlefttitle" style="border-right: solid 2px white; padding-right: 1.5%;" onclick="location.href='@Url.Action("Index", "Home")'">Shiba Central</a>
                        <a class="textleft" style="margin-left:1.3%;" onclick="location.href='@Url.Action("Index", "Store")'">Store</a>
                        <a class="textleft" href="https://www.w3schools.com">Community</a>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <a class="textright" onclick="location.href='@Url.Action("Index", "MyPage")'">My Page</a>

                            <a class="textright" onclick="location.href='@Url.Action("Logout", "Login")'">Logout</a>
                        }
                        else
                        {
                            <a class="textright" onclick="location.href='@Url.Action("Register", "Login")'">Register</a>

                            <a class="textright" onclick="location.href='@Url.Action("Index", "Login")'">Login</a>
                        }


                    </div>
                </div>




            </div>


        </div>
        <div class="logindiv">
            <h1 class="middletexttitle">
                Login
            </h1>
            <p class="success">
                You have been successfully logged in! :)
            </p>


        </div>

        <div id="pagefooter">
            <img class="shibahead" src="~/Resources/Images/shibahead.png" />
            <h1 class="footertitle">SHIBA CENTRAL™</h1>
            <ul class="footerlist">
                <li style="border:none;"><a href="https://www.w3schools.com"><p>CAREERS</p></a></li>
                <li><a href="https://www.w3schools.com"><p>ABOUT</p></a></li>
                <li><a href="https://www.w3schools.com"><p>SUPPORT</p></a></li>
                <li><a href="https://www.w3schools.com"><p>CONTACT US</p></a></li>
                <li><a href="https://www.w3schools.com"><p>PRESS</p></a></li>

            </ul>

            <p class="legaltext" style="font-size: 15px; margin-top: 1.7%; margin-bottom: 2%;">
                ©2018 SHIBA CENTRAL, INC. ALL RIGHTS RESERVED.
                <br />
                All trademarks referenced herein are the properties of their respective owners.
            </p>
        </div>
    </div>
</body>
</html>

ShibaStoreProject/Views/Login/SuccessfulRegister.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Fredoka+One|Open+Sans:700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
</head>
<body>
    <div class="backgroundimage">
        <div class="shibastoretop">
            <div id="mainpage">
                <div class="shibaheaderstore">
                    <div class="headertext">
                        <a class="textlefttitle" style="border-right: solid 2px white; padding-right: 1.5%;" onclick="location.href='@Url.Action("Index", "Home")'">Shiba Central</a>
                        <a class="textleft" style="margin-left:1.3%;" onclick="location.href='@Url.Action("Index", "Store")'">Store</a>
                        <a class="textleft" href="https://www.w3schools.com">Community</a>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <a class="textright" onclick="location.href='@Url.Action("Index", "MyPage")'">My Page</a>

                            <a class="textright" onclick="location.href='@Url.Action("Logout", "Login")'">Logout</a>
                        }
                        else
                        {
                            <a class="textright" onclick="location.href='@Url.Action("Register", "Login")'">Register</a>

                            <a class="textright" onclick="location.href='@Url.Action("Index", "Login")'">Login</a>
                        }


                    </div>
                </div>




            </div>


        </div>
        <div class="logindiv">
            <h1 class="middletexttitle">
                Login
            </h1>
            <p class="success">
                You have been successfully registered! :)
            </p>


        </div>

        <div id="pagefooter">
            <img class="shibahead" src="~/Resources/Images/shibahead.png" />
            <h1 class="footertitle">SHIBA CENTRAL™</h1>
            <ul class="footerlist">
                <li style="border:none;"><a href="https://www.w3schools.com"><p>CAREERS</p></a></li>
                <li><a href="https://www.w3schools.com"><p>ABOUT</p></a></li>
                <li><a href="https://www.w3schools.com"><p>SUPPORT</p></a></li>
                <li><a href="https://www.w3schools.com"><p>CONTACT US</p></a></li>
                <li><a href="https://www.w3schools.com"><p>PRESS</p></a></li>

            </ul>

            <p class="legaltext" style="font-size: 15px; margin-top: 1.7%; margin-bottom: 2%;">
                ©2018 SHIBA CENTRAL, INC. ALL RIGHTS RESERVED.
                <br />
                All trademarks referenced herein are the properties of their respective owners.
            </p>
        </div>
    </div>
</body>
</html>

ShibaStoreProject/Views/MyPage/Index.cshtml
@model List<ShibaStoreProject.Dog>


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Fredoka+One|Open+Sans:700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">



</head>
<body>


    <script type='text/javascript'>


    </script>

    <div class="backgroundimage">
        <div class="shibastoretop">
            <div id="mainpage">
                <div class="shibaheaderstore">
                    <div class="headertext">
                        <a class="textlefttitle" style="border-right: solid 2px white; padding-right: 1.5%;" onclick="location.href='@Url.Action("Index", "Home")'">Shiba Central</a>
                        <a class="textleft" style="margin-left:1.3%;" onclick="location.href='@Url.Action("Index", "Store")'">Store</a>
                        <a class="textleft" href="https://www.w3schools.com">Community</a>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <a class="textright" onclick="location.href='@Url.Action("Index", "MyPage")'">My Page</a>

                            <a class="textright" onclick="location.href='@Url.Action("Logout", "Login")'">Logout</a>
                        }
                        else
                        {
                            <a class="textright" onclick="location.href='@Url.Action("Register", "Login")'">Register</a>

                            <a class="textright" onclick="location.href='@Url.Action("Index", "Login")'">Login</a>
                        }


                    </div>
                </div>
            </div>




            <div class="dogstorecontainer" style="display:inherit;">
                <h1 class="middletexttitle">
                    These are your dogs
                </h1>


                <div>


                    @if (Model.Count() == 0)
                    {
                        <p class="dogdesc" style="color:darkgray;">
                            You don't have any dogs in your wishlist. :(
                        </p>

                    }
                    else
                    {
                        <ul class="selectorlist">
                            @foreach (var dog in Model)
                            {
                                <li>
                                    <div class="dogselector">
                                        <a><img class="selectorimagepage" id="@(dog.DogName + "selector")" src="@("/Resources/Images/" + dog.ImageName)" /></a>
                                    </div>
                                    <p class="selectortext">@dog.DogName</p>
                                    @using (Html.BeginForm())
                                    {

                                        <input style="display:none;" type="number" name="dogID" id="selectedid" value="@dog.DogID" />
                                        <p class="wishbuttontext">
                                            <input class="wishbutton" type="submit" value="Remove this dog" />
                                        </p>

                                    }
                                </li>
                            }
                        </ul>
                    }
                </div>
            </div>

        </div>
        <div id="pagefooter">
            <img class="shibahead" src="~/Resources/Images/shibahead.png" />
            <h1 class="footertitle">SHIBA CENTRAL™</h1>
            <ul class="footerlist">
                <li style="border:none;"><a href="https://www.w3schools.com"><p>CAREERS</p></a></li>
                <li><a href="https://www.w3schools.com"><p>ABOUT</p></a></li>
                <li><a href="https://www.w3schools.com"><p>SUPPORT</p></a></li>
                <li><a href="https://www.w3schools.com"><p>CONTACT US</p></a></li>
                <li><a href="https://www.w3schools.com"><p>PRESS</p></a></li>

            </ul>

            <p class="legaltext" style="font-size: 15px; margin-top: 1.7%; margin-bottom: 2%;">
                ©2018 SHIBA CENTRAL, INC. ALL RIGHTS RESERVED.
                <br />
                All trademarks referenced herein are the properties of their respective owners.
            </p>
        </div>




    </div>
</body>
</html>

ShibaStoreProject/Views/Store/Index.cshtml
@model List<ShibaStoreProject.Dog>


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Fredoka+One|Open+Sans:700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">



</head>
<body>


    <script type='text/javascript'>


    </script>

    <div class="backgroundimage">
        <div class="shibastoretop">
            <div id="mainpage">
                <div class="shibaheaderstore">
                    <div class="headertext">
                        <a class="textlefttitle" style="border-right: solid 2px white; padding-right: 1.5%;" onclick="location.href='@Url.Action("Index", "Home")'">Shiba Central</a>
                        <a class="textleft" style="margin-left:1.3%;" onclick="location.href='@Url.Action("Index", "Store")'">Store</a>
                        <a class="textleft" href="https://www.w3schools.com">Community</a>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <a class="textright" onclick="location.href='@Url.Action("Index", "MyPage")'">My Page</a>

                            <a class="textright" onclick="location.href='@Url.Action("Logout", "Login")'">Logout</a>
                        }
                        else
                        {
                            <a class="textright" onclick="location.href='@Url.Action("Register", "Login")'">Register</a>

                            <a class="textright" onclick="location.href='@Url.Action("Index", "Login")'">Login</a>
                        }


                    </div>
                </div>
            </div>


            @foreach (var dog in Model)
            {
                <div class="dogstorecontainer" id="@(dog.DogID + "container")">

                    <br />

                    <img class="storeimage" id="selecteddogimage" src="@("/Resources/Images/" + dog.ImageName)" />

                    <div class="storetextcontainer">
                        <h1 class="dogname" id="selectedname">
                            @dog.DogName
                        </h1>
                        <p class="dogdesc" id="selecteddesc">
                            @dog.DogDesc
                        </p>
                        @if (User.Identity.IsAuthenticated)
                        {

                            StoreDBEntities db = new StoreDBEntities();
                            var uID = Convert.ToInt32(System.Web.HttpContext.Current.Session["sessionID"]);

                            User users = db.Users.First(i => i.UserID == uID);

                            if (db.Dogs.FirstOrDefault(i => i.DogID == dog.DogID && i.Users.Any(t => t.UserID == uID)) != null)
                            {
                                <p class="dogdesc" style="color:darkgray;">
                                    This dog is already in your wishlist. :)
                                </p>
                                <input style="display:none;" type="number" name="dogID" id="selectedid" value="@dog.DogID" />
                            }
                            else
                            {
                                using (Html.BeginForm())
                                {

                                    <input style="display:none;" type="number" name="dogID" id="selectedid" value="@dog.DogID" />
                                    <p class="wishbuttontext">
                                        <input class="wishbutton" type="submit" value="Wish this dog" />
                                    </p>

                                }
                            }
                        }
                        else
                        {
                            <input style="display:none;" type="number" name="dogID" id="selectedid" value="@dog.DogID" />
                            <p class="dogdesc" style="color:darkgray;">You have to be <span class="loginspan" style="color:orange;"><a onclick="location.href='@Url.Action("Index", "Login")'">logged in</a></span> to add this dog to your wishlist. :(</p>
                        }
                    </div>
                </div>
            }
        </div>



        <div id="pagemiddle" style="overflow:auto;">
            <h1 class="middletexttitle">
                These are our dogs
            </h1>


            <div>
                <ul class="selectorlist">
                    @foreach (var dog in Model)
                    {
                    <li>
                        <div class="dogselector">
                            <a onclick="SetDog('@dog.DogName','@dog.DogDesc', '@dog.ImageName', '@(dog.DogName + "selector")', '@dog.DogID')"><img class="selectorimage" id="@(dog.DogName + "selector")" src="@("/Resources/Images/" + dog.ImageName)" /></a>
                        </div>
                        <p class="selectortext">@dog.DogName</p>
                       
                    </li>
                    }
                </ul>
            </div>



        </div>

    </div>
    <div id="pagefooter">
        <img class="shibahead" src="~/Resources/Images/shibahead.png" />
        <h1 class="footertitle">SHIBA CENTRAL™</h1>
        <ul class="footerlist">
            <li style="border:none;"><a href="https://www.w3schools.com"><p>CAREERS</p></a></li>
            <li><a href="https://www.w3schools.com"><p>ABOUT</p></a></li>
            <li><a href="https://www.w3schools.com"><p>SUPPORT</p></a></li>
            <li><a href="https://www.w3schools.com"><p>CONTACT US</p></a></li>
            <li><a href="https://www.w3schools.com"><p>PRESS</p></a></li>

        </ul>

        <p class="legaltext" style="font-size: 15px; margin-top: 1.7%; margin-bottom: 2%;">
            ©2018 SHIBA CENTRAL, INC. ALL RIGHTS RESERVED.
            <br />
            All trademarks referenced herein are the properties of their respective owners.
        </p>
    </div>

    

    <script type="text/javascript">
        var selectedDogID = "";
        var previousDogID = "";

        var selectedSelector = "";
        var previousSelector = "";

        function SetDog(dogname, dogdesc, dogimage, dogselector, dogid) {

            if (dogselector == selectedDogID) {
                return;
            }
            document.getElementById(previousDogID).style.webkitFilter = "brightness(80%)";
            document.getElementById(previousDogID).style.transform = "unset";
            document.getElementById(previousSelector + "container").style.display = "none";

            selectedDogID = dogselector;
            previousDogID = selectedDogID;

            selectedSelector = dogid;
            previousSelector = selectedSelector;

            document.getElementById(dogid + "container").style.display = "flex";
            document.getElementById("selectedname").innerHTML = dogname;
            document.getElementById("selecteddesc").innerHTML = dogdesc;
            document.getElementById("selectedid").value = dogid;


            
            document.getElementById("selecteddogimage").src = "/Resources/Images/" + dogimage;
            document.getElementById(dogselector).style.transform = "scale(1.2)";
            document.getElementById(dogselector).style.webkitFilter = "brightness(130%)";
        }

        function SetDogs() {


            document.getElementById('@(Model[0].DogID + "container")').style.display = "flex";
            document.getElementById('@(Model[0].DogName + "selector")').style.transform = "scale(1.2)";
            document.getElementById('@(Model[0].DogName + "selector")').style.webkitFilter = "brightness(120%)";
            previousDogID = '@(Model[0].DogName + "selector")';
            previousSelector = @Model[0].DogID;
        }


        
        window.onload = SetDogs()

       
        
    </script>
</body>
</html>